### ISSUE TITLE
balanceOfToken should be a view.

### ISSUE THREAD

**Issue by steffenix** [pooltogether/yield-source-interface#4]
https://github.com/pooltogether/yield-source-interface/blob/4d51a473f40407665a1c7bf8c153566a6de0e561/contracts/IYieldSource.sol#L15

**Comment by steffenix** [comment]
What's about this one @asselstine ?

**Comment by asselstine** [comment]
Actually, it shouldn't be!  I know it's counter-intuitive

There are systems whose yield must be calculated up to the block, or second, and in order for them to work they need to run non-constant functions.

A good example of this is the Compound cToken balanceOfUnderlying function.  It needs to update the interest rate to calculate the correct underlying balance of the shares.
